[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Gestion des redirections pour le routing côté client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200