[build]
  command = "npm run build"
  publish = "out"  # Changé de ".next" vers "out"

# Suppression du plugin Next.js car on utilise l'export statique
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Gestion des redirections pour le routing côté client
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200